LIBRERUMTEST/Models/ClienteModel.cs
using System.ComponentModel.DataAnnotations;

namespace LIBRERUMTEST.Models
{
    public class ClienteModel
    {
        [Required(ErrorMessage = "El campo Cedula es obligatorio")]
        public string? Cedula { get; set; }
        [Required(ErrorMessage = "El campo Nombres es obligatorio")]
        public string? Nombres { get; set; }
        [Required(ErrorMessage = "El campo Telefono es obligatorio")]
        public string? Telefono { get; set; }
        [Required(ErrorMessage = "El campo Direccion es obligatorio")]
        public string? Direccion { get; set; }



    }
}

LIBRERUMTEST/Models/ErrorViewModel.cs
namespace LIBRERUMTEST.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LIBRERUMTEST/Models/VentaModel.cs
using System.ComponentModel.DataAnnotations;

namespace LIBRERUMTEST.Models
{
    public class VentaModel
    {
        [Required(ErrorMessage = "El campo CodigoVenta es obligatorio")]
        public string? CodigoVenta { get; set; }
        [Required(ErrorMessage = "El campo CodigoProducto es obligatorio")]
        public string? CodigoProducto { get; set; }
        [Required(ErrorMessage = "El campo FechaVenta es obligatorio")]
        public string? FechaVenta { get; set; }
        [Required(ErrorMessage = "El campo PuntoVenta es obligatorio")]
        public string? PuntoVenta { get; set; }
        [Required(ErrorMessage = "El campo Total es obligatorio")]
        public decimal Total { get; set; }

        public ClienteModel? ClienteModel { get; set; }
    }
}

LIBRERUMTEST/Controllers/ClienteController.cs
using LIBRERUMTEST.Datos;
using LIBRERUMTEST.Models;
using Microsoft.AspNetCore.Mvc;

namespace LIBRERUMTEST.Controllers
{
    public class ClienteController : Controller
    {

        ClienteDatos _ClienteDatos = new ClienteDatos();

        public IActionResult Listar()
        {
            //La vista mostrara una lista de contactos
            var oLista = _ClienteDatos.Listar();

            return View(oLista);
        }

        public IActionResult Guardar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Guardar(ClienteModel oCliente)
        {
            //Metodo recibe el objeto para guardarlo en BD
            if (!ModelState.IsValid)
                return View();

            var respuesta = _ClienteDatos.Guardar(oCliente);

            if (respuesta)
                return RedirectToAction("Listar"); // me retorna al metodo donde tengo todos los contactos registrados
            else
                return View(); // retorna la misma vista para volver a guardar porque ha fallido
        }
    }
}

LIBRERUMTEST/Controllers/HomeController.cs
using LIBRERUMTEST.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LIBRERUMTEST.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LIBRERUMTEST/Controllers/VentaController.cs
using LIBRERUMTEST.Datos;
using LIBRERUMTEST.Models;
using Microsoft.AspNetCore.Mvc;

namespace LIBRERUMTEST.Controllers
{

    public class VentaController : Controller
    {
        VentaDatos _VentaDatos = new VentaDatos();

        public IActionResult Listar()
        {
            //La vista mostrara una lista de _VentaDatos
            var oLista = _VentaDatos.Listar();

            return View(oLista);
        }

        public IActionResult Guardar()
        {
            //Metodo solo devuelve la vista
            return View();
        }


        [HttpPost]
        public IActionResult Guardar(VentaModel oVenta)
        {
            ClienteModel cliente = new ClienteModel();
            ClienteDatos clienteDatos = new ClienteDatos();
            cliente = clienteDatos.Obtener(oVenta.ClienteModel.Cedula);
            if(cliente == null) 
                return BadRequest();

            oVenta.ClienteModel = cliente;
            //Metodo recibe el objeto para guardarlo en BD
            //if (!ModelState.IsValid)
            //    return View();

            var respuesta = _VentaDatos.Guardar(oVenta);

            if (respuesta)
                return RedirectToAction("Listar"); // me retorna al metodo donde tengo todos los contactos registrados
            else
                return View(); // retorna la misma vista para volver a guardar porque ha fallido
        }

        public IActionResult Editar(int CodigoVenta)
        {
            //Metodo solo devuelve la vista
            var ocontacto = _VentaDatos.Obtener(CodigoVenta);
            return View(ocontacto);
        }

        [HttpPost]
        public IActionResult Editar(VentaModel oVenta)
        {

            if (!ModelState.IsValid)
                return View();

            var respuesta = _VentaDatos.Editar(oVenta);

            if (respuesta)
                return RedirectToAction("Listar"); // me retorna al metodo donde tengo todos los contactos registrados
            else
                return View(); // retorna la misma vista para volver a guardar porque ha fallido
        }

        public IActionResult Eliminar(int CodigoVenta)
        {
            //Metodo solo devuelve la vista
            var ocontacto = _VentaDatos.Obtener(CodigoVenta);
            return View(ocontacto);
        }

        [HttpPost]
        public IActionResult Eliminar(VentaModel oVenta)
        {


            var respuesta = _VentaDatos.Eliminar(oVenta.CodigoVenta);

            if (respuesta)
                return RedirectToAction("Listar"); // me retorna al metodo donde tengo todos los contactos registrados
            else
                return View(); // retorna la misma vista para volver a guardar porque ha fallido
        }
    }
}

LIBRERUMTEST/Views/Cliente/Guardar.cshtml
@model ClienteModel
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Crear Cliente
    </div>
    <div class="card-body">

        <form asp-action="Guardar" asp-controller="Cliente" method="post">
             <div class="mb-3">
                <label  class="form-label">Cedula</label>
                <input asp-for="Cedula" type="text" class="form-control"  >
                <span asp-validation-for="Cedula" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label  class="form-label">Nombres</label>
                <input asp-for="Nombres" type="text" class="form-control"  >
                <span asp-validation-for="Nombres" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label  class="form-label">Telefono</label>
                <input asp-for="Telefono" type="text" class="form-control">
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Direccion</label>
                <input asp-for="Direccion" type="text" class="form-control">
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Listar"  asp-controller="Cliente"  class="btn btn-warning">Volver a la lista</a>
        </form>

    </div>
</div>

LIBRERUMTEST/Views/Cliente/Listar.cshtml
@model List<ClienteModel>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Lista Clientes
    </div>
    <div class="card-body">
        <a asp-action="Guardar" asp-controller="Cliente" class="btn btn-success">Crear Nuevo</a>
        <hr />
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Cedula</th>
                    <th>Nombres</th>
                    <th>Telefono</th>
                    <th>Direccion</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model)
                {
                    <tr>
                        <td>@item.Cedula</td>
                        <td>@item.Nombres</td>
                        <td>@item.Telefono</td>
                        <td>@item.Direccion</td>
                        <td>
@*                            <a asp-action="Editar" asp-controller="Mantenedor" class="btn btn-primary btr-sm" asp-route-IdContacto="@item.IdContacto">Editar</a>
                            <a asp-action="Eliminar" asp-controller="Mantenedor" class="btn btn-danger btr-sm" asp-route-IdContacto="@item.IdContacto">Eliminar</a>*@
                        </td>
                    </tr>
                }
            </tbody>

        </table>
           

    </div>
</div>

LIBRERUMTEST/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LIBRERUMTEST/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LIBRERUMTEST</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LIBRERUMTEST.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LIBRERUMTEST</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Venta" asp-action="listar">Ventas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Listar">Clientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LIBRERUMTEST - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LIBRERUMTEST/Views/Venta/Guardar.cshtml
@model VentaModel
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Crear Venta
    </div>
    <div class="card-body">

        <form asp-action="Guardar" asp-controller="Venta" method="post">
            <div class="mb-3">
                <label  class="form-label">CodigoVenta</label>
                <input asp-for="CodigoVenta" type="text" class="form-control"  >
                <span asp-validation-for="CodigoVenta" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label  class="form-label">CodigoProducto</label>
                <input asp-for="CodigoProducto" type="text" class="form-control"  >
                <span asp-validation-for="CodigoProducto" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label  class="form-label">FechaVenta</label>
                <input asp-for="FechaVenta" type="text" class="form-control">
                <span asp-validation-for="FechaVenta" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">PuntoVenta</label>
                <input asp-for="PuntoVenta" type="text" class="form-control">
                <span asp-validation-for="PuntoVenta" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">CedulaCliente</label>
                <input asp-for="ClienteModel.Cedula" type="text" class="form-control">
                <span asp-validation-for="ClienteModel.Cedula" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Total</label>
                <input asp-for="Total" type="text" class="form-control">
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Listar"  asp-controller="Venta"  class="btn btn-warning">Volver a la lista</a>
        </form>

    </div>
</div>

LIBRERUMTEST/Views/Venta/Listar.cshtml
@model List<VentaModel>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Lista ventas
    </div>
    <div class="card-body">
        <a asp-action="Guardar" asp-controller="Venta" class="btn btn-success">Crear Nuevo</a>
        <hr />
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>CodigoVenta</th>
                    <th>CodigoProducto</th>
                    <th>FechaVenta</th>
                    <th>PuntoVenta</th>
                    <th>CedulaCliente</th>
                    <th>Total</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model)
                {
                    <tr>
                        <td>@item.CodigoVenta</td>
                        <td>@item.CodigoProducto</td>
                        <td>@item.FechaVenta</td>
                        <td>@item.PuntoVenta</td>
                        <td>@item.ClienteModel.Cedula</td>
                        <td>@item.ClienteModel.Nombres</td>
                        <td>@item.ClienteModel.Telefono</td>
                        <td>@item.ClienteModel.Direccion</td>
                        <td>@item.Total</td>
                        <td>
                            <a asp-action="Editar" asp-controller="Venta" class="btn btn-primary btr-sm" asp-route-IdContacto="@item.CodigoVenta">Editar</a>
                                <a asp-action="Eliminar" asp-controller="Venta" class="btn btn-danger btr-sm" asp-route-IdContacto="@item.CodigoVenta">Eliminar</a>
                        </td>
                    </tr>
                }
            </tbody>

        </table>
           

    </div>
</div>